networks:
  ray_network:
    driver: bridge


services:
  ray_head:
    image: rayproject/ray:latest
    command: >
      bash -c "ray start --head --port=6379 --dashboard-host=0.0.0.0 && tail -f /dev/null"
    ports:
      - "6379:6379"  # Port do komunikacji między węzłami Ray
      - "8265:8265" # Port do dashboarda ray
    environment:
      - RAY_ADDRESS=ray://ray_head:6379
    restart: unless-stopped
    shm_size: "4g"
    depends_on:
      - db
      - mlflow
    networks:
      - ray_network

  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - RAY_ADDRESS=ray_head:6379 # czy to jest poprawny adres?
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    volumes:
      - ./src:/app
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    restart: unless-stopped
    depends_on:
      - mlflow
      - ray_head
      - db
    networks:
      - ray_network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    command: /bin/sh -c "pip install psycopg2-binary && mlflow server --backend-store-uri postgresql://mlflow:mlflow@db/mlflow --default-artifact-root /mlflow --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@db/mlflow
      - MLFLOW_ARTIFACT_URI=/mlflow
    volumes:
      - ./mlruns:/mlflow
    depends_on:
      - db
    networks:
      - ray_network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ray_network
