
services:
  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    volumes:
      - ./src:/app
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    restart: unless-stopped
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    command: /bin/sh -c "pip install psycopg2-binary && mlflow server --backend-store-uri postgresql://mlflow:mlflow@db/mlflow --default-artifact-root /mlflow --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@db/mlflow
      - MLFLOW_ARTIFACT_URI=/mlflow
    volumes:
      - ./mlruns:/mlflow
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
