version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow_pass
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_server
    restart: always
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow:mlflow_pass@postgres:5432/mlflow_db
    command: mlflow server --backend-store-uri postgresql://mlflow:mlflow_pass@postgres:5432/mlflow_db --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
