# docker-compose.yml
version: '3.8'

services:
  trainer:
    image: dice-ocr
    build:
      context: ..
      dockerfile: docker/Dockerfile
    deploy:
      mode: replicated
      replicas: 4  # liczba kontenerów dla równoległych eksperymentów
    volumes:
      - ../src:/app
      - ../optuna_study.db:/app/optuna_study.db
    network_mode: "host"

